#!/bin/sh
# option check
if [ $# -lt 3 ]
then
  echo "usage: $0 <modem number> <phone number> <text>"
  exit 1
fi
MODEM=$1
NUMBER=$2
TEXT=$3
RET_TEXT=$(mmcli -m $MODEM --messaging-create-sms="text='$TEXT',number='$NUMBER'")
SMS_ID=$(echo "$RET_TEXT" | awk -F '/' '{print $6}' | awk -F ' ' '{print $1}')
#echo $RET_TEXT
#echo $SMS_ID
mmcli -s $SMS_ID --send
