.TH "mmsendsms" 1 0.0.1 "07 Mar 2021" "User Manual"

.SH NAME
mmsendsms

.SH DESCRIPTION
This is a simple SMS send frontend for modemmanager. You can list your modems like this: "mmcli -L". You can send an SMS over modem 0 like this: "mmsendsms 0 +49xxxxxx" "your text"



.SH SYNOPSIS
mmsendsms [modem number] [phone number] [text message]


.SH FILES
.TP
All SMS are stored in ~/.mmsmsd

.SH COPYRIGHT
mmsendsms:

Copyright (c) 2021 U. Niethammer

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

.SH SEE ALSO
 mmsmsd(1)

.SH CONTACT
 Website: https://github.com/dr-ni/mmsmsd

